### PR TITLE
Unbold the no-armor header, so the strikethrough is more obvious.

### PR DESCRIPTION
**Pull request by johnlamping**

### CODE REVIEW

**Comment by johnlamping** [comment]
This isn't working, because the new style is getting overridden by the bold style. I'm looking for the right way to make this work with scss.

**Comment by johnlamping** [comment]
Learned about !important.

**Review by jazeee — APPROVED** [review]
Important is generally frowned on, because it results in a bit of a css battle.
That being said, we have some tricky css to wrangle, yet.
Nice fix.

**Comment by johnlamping** [comment]
Do you want to approve it, Jaz, or await a better solution?

**Comment by jazeee** [comment]
I approved it already. Feel free to merge

**Pull request merged**
